# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"
  repositories:
    profiles:
      repo: "git@gitlab.virtua.vm:puppet/profiles.git"
      branch: development
    ntp:
      repo: "git@gitlab.virtua.vm:puppet/ntp.git"
      branch: development
    ldapclient:
      repo: "git@gitlab.virtua.vm:puppet/ldapclient.git"
      branch: development
    ssh:
      repo: "git@gitlab.virtua.vm:puppet/ssh.git"
      branch: development
    pam:
      repo: "git@gitlab.virtua.vm:puppet/pam.git"
      branch: development
    autofs:
      repo: "git@gitlab.virtua.vm:puppet/autofs.git"
      branch: development
    rsyslog:
      repo: "git@gitlab.virtua.vm:puppet/rsyslog.git"
      branch: development